### ISSUE TITLE
Doesn't Work With ShadowSocks.

### ISSUE THREAD

**Issue by jglimmers** [We5ter/GSDF#2]
Processing...,The result may be numerous.so please wait for a while.
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Sorry,timeout or network is not smooth

**Comment by We5ter** [comment]
These words 'Sorry,timeout or network is not smooth' exist in `GSDFT.py`,so I guess that you have downloaded a wrong script,you need to download `GSDFT.py`,then edit proxy,not `GSDTA.py`

Could you check it again?

**Comment by jglimmers** [comment]
1.git clone https://github.com/We5ter/GSDF.git
2. cd GSDF/
3. vim GSDFT.py 
    
![image](https://user-images.githubusercontent.com/9823869/32211850-6a67891c-be4f-11e7-98e3-bc0e70589253.png)
4. python GSDFT.py
    find twitter.com
![image](https://user-images.githubusercontent.com/9823869/32211888-9ea3498c-be4f-11e7-8bf8-8c9d3d5951ab.png)

Was there anything wrong?

**Comment by We5ter** [comment]
This means python script cannot connect to your shadowsocks server. Could you check your PC run with a global proxy?

I guess you only configure the shadowsocks proxy in browser based on your picture,other applications cannot connect to google.

**Comment by jglimmers** [comment]
No, other apps can connect to ShadowSocks Server. I guess it's my network routing problem. I'll figure it out later.

**Comment by We5ter** [comment]
You can ping `192.168.40.1` to test the connection from command,or use a temporary python script to test network connection.

**Comment by We5ter** [comment]
OK,if you have another question, please let me know. Thank you for your feedback.
