### ISSUE TITLE
seems google's sct site down constantly??

### ISSUE THREAD

**Issue by Justsoos** [We5ter/GSDF#3]
```
[root@localhost GSDF]# proxychains4 python3 GSDFT.py -d google.com -e hide
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12

    `______`````______`````_____`````______``
    /\``___\```/\``___\```/\``__-.``/\``___\`
    \`\`\__`\``\`\___``\``\`\`\/\`\`\`\``__\`
    `\`\_____\``\/\_____\``\`\____-``\`\_\```
    ``\/_____/```\/_____/```\/____/```\/_/```
    `````````````````````````````````````````
       Author:Wester@Sixtant Security Lab
    
[+]Searching subdomains for google.com
[proxychains] Strict chain  ...  192.168.1.100:1080  ...  transparencyreport.google.com:443 <--socket error or timeout!
[+]Error exit...
```

btw, I use proxychains-ng, nice and easy tool.
I tried in hours ....  and there is no further info in GSDF/log folder ...

and another question of GSDF, I can not enter the Terminal window as that it is said with `python3 GSDFT.py`, only give me the usage help, like this:

```
[root@localhost GSDF]# proxychains4 python3 GSDFT.py 
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12

    `______`````______`````_____`````______``
    /\``___\```/\``___\```/\``__-.``/\``___\`
    \`\`\__`\``\`\___``\``\`\`\/\`\`\`\``__\`
    `\`\_____\``\/\_____\``\`\____-``\`\_\```
    ``\/_____/```\/_____/```\/____/```\/_/```
    `````````````````````````````````````````
       Author:Wester@Sixtant Security Lab
    
usage: GSDFT.py [-h] -d SEARCH_DOMAIN [-s SAVE_PATH] -e SHOW_EXPIRED
GSDFT.py: error: the following arguments are required: -d/--domain, -e/--expired

```

I HAVE to run with -d and -e, is it right?  I run it in Centos 7, python 3.4.5

**Comment by We5ter** [comment]
For Q1：
Maybe you should try this,and the proxy IP/port is your proxy IP/port:
![gsdf](https://user-images.githubusercontent.com/8722530/35559347-874da240-05e5-11e8-8d86-7a92c2b317d2.PNG)
And you need add `proxies=self.proxies` to all the following `req = requests.get()`
![req](https://user-images.githubusercontent.com/8722530/35559422-b61564a0-05e5-11e8-83e2-03137cbb2820.PNG)

For Q2:
The correct usage is :`python GSDFT.py -d google.com -e show`.
The default save folder is `log`,and you should ensure your script can write into this path.

**Comment by We5ter** [comment]
Can you ensure you can access google.com through 192.168.1.100:1080?

Maybe these articles  can help you:
https://bbs.archlinux.org/viewtopic.php?id=206960
https://github.com/rofl0r/proxychains-ng/issues/87

**Comment by Justsoos** [comment]
not the problem of proxy. but line:
https://github.com/We5ter/GSDF/blob/master/GSDFT.py#L82
`rep = (req.text).encode('utf-8').lstrip(")]}'")`
the utf-8 encode transfer 'str' to 'bytes', it brought the error in python ver 3.
it might be 
`rep = (req.text)lstrip(")]}'")`
 but, after this correction, still got wrong output:

```
  12640 subdomain certificate logs found
[+]Error exit..
```

**Comment by We5ter** [comment]
Yes,I just test it on python2.7.

**Comment by We5ter** [comment]
Could you tell me what does your command look like?

**Comment by We5ter** [comment]
![gsdf](https://user-images.githubusercontent.com/8722530/35657940-0013cfb0-073a-11e8-8171-5c173753304a.PNG)

**Comment by Justsoos** [comment]
... faint ... I tried within python2.7, it started downloading, well with proxychains too.
I have NOT seen the python2.7 on project home page yet ...

but still get ssl error, can not save the result of show in terminal:
`EOF occurred in violation of protocol (_ssl.c:590)
[+]Error exit...`

as the advice of requests author, better using session instead of, so I make a pull request, wait for me mins.
https://github.com/requests/requests/issues/3391#issuecomment-231576728

**Comment by Justsoos** [comment]
seems requests.Session().get much stronger than requests.get, all is well

**Comment by We5ter** [comment]
OK,have a nice day!
